export const OPERATORS_DATABASE = [
  { id: 1, nome: "Lucas Silva", matricula: "123"},
  { id: 2, nome: "João Santos", matricula: "124"},
  { id: 3, nome: "Maria Oliveira", matricula: "125"},
  { id: 4, nome: "Carlos Costa", matricula: "126"},
  { id: 5, nome: "Ana Ferreira", matricula: "127"},
]

export const RA_DATABASE = [
  { numero: "I", nome: "PLANO PILOTO" },
  { numero: "II", nome: "GAMA" },
  { numero: "III", nome: "TAGUATINGA" },
  { numero: "IV", nome: "BRAZLÂNDIA" },
  { numero: "V", nome: "SOBRADINHO" },
  { numero: "VI", nome: "PLANATINA" },
  { numero: "VII", nome: "PARANÃ" },
  { numero: "VIII", nome: "NÚCLEO BANDEIRANTE" },
  { numero: "IX", nome: "CEILÂNDIA" },
  { numero: "X", nome: "GUARÁ" },
  { numero: "XI", nome: "CRUZEIRO" },
  { numero: "XII", nome: "SAMAMBAIA" },
  { numero: "XIII", nome: "SANTA MARIA" },
  { numero: "XIV", nome: "SÃO SEBASTIÃO" },
  { numero: "XV", nome: "RECANTO DAS EMAS" },
  { numero: "XVI", nome: "LAGO SUL" },
  { numero: "XVII", nome: "RIACHO FUNDO" },
  { numero: "XVIII", nome: "LAGO NORTE" },
  { numero: "XIX", nome: "CANDANGOLÂNDIA" },
  { numero: "XX", nome: "ÁGUAS CLARAS" },
  { numero: "XXI", nome: "RIACHO FUNDO 2" },
  { numero: "XXII", nome: "SUDOESTE" },
  { numero: "XXIII", nome: "VARJÃO" },
  { numero: "XXIV", nome: "PARK WAY" },
  { numero: "XXV", nome: "ESTRUTURAL" },
  { numero: "XXVI", nome: "JARDIM BOTÂNICO" },
  { numero: "XXVII", nome: "ITAPOÃ" },
  { numero: "XXVIII", nome: "SIA" },
  { numero: "XXIX", nome: "VICENTE PIRES" },
  { numero: "XXX", nome: "FERCAL" },
  { numero: "XXXI", nome: "SOL NASCENTE" },
  { numero: "XXXII", nome: "ARNIQUEIRA" },
  { numero: "XXXIII", nome: "ÁGUA QUENTE" },
]

export const SERVICOS = [
  { id: "aceiramento", label: "Aceiramento", unidade: "km" },
  { id: "compactacao", label: "Compactação", unidade: "km" },
  { id: "nivelamento", label: "Nivelamento", unidade: "m²" },
  { id: "coiva", label: "Coiva (abertura)", unidade: "UD" },
  { id: "peito", label: "Peito de Pombo", unidade: "UD" },
  { id: "revitalizacao", label: "Revitalização Canal", unidade: "m" },
  { id: "destoca", label: "Destoca", unidade: "ha" },
  { id: "rocagem", label: "Rocagem", unidade: "ha" },
  { id: "aterramento", label: "Aterramento de vala", unidade: "m" },
  { id: "distribuicao", label: "Distribuição adubo", unidade: "ha" },
  { id: "drenagem", label: "Drenagem de Estradas", unidade: "m" },
  { id: "subsodagem", label: "Subsodagem", unidade: "ha" },
  { id: "barramento", label: "Barramento (recuperação)", unidade: "UD" },
  { id: "sulcagem", label: "Sulcagem", unidade: "ha" },
  { id: "escavacao", label: "Escavação", unidade: "m" },
  { id: "tanque", label: "Tanque (reparo)", unidade: "UD" },
  { id: "tanque_abertura", label: "Tanque (abertura)", unidade: "UD" },
  { id: "terraco", label: "Terraco (construção)", unidade: "ha" },
  { id: "terraco_reparo", label: "Terraco (reparo)", unidade: "ha" },
  { id: "transporte", label: "Transporte", unidade: "km" },
]
